(toggle-debug-on-error)
(require 'package)
(package-initialize)
(require 'org)
(require 'htmlize)
(require 'rainbow-delimiters)
(require 'dockerfile-mode)
(require 'json-mode)
(require 'yaml-mode)
(with-eval-after-load 'rainbow-delimiters
  (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
(with-eval-after-load 'org
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((shell . t)
     (js . t)
     (emacs-lisp . t)
     (clojure . t)
     (python . t)
     (ruby . t)
     (dot . t)
     (css . t)
     (plantuml . t)))
  (add-to-list 'org-src-lang-modes '("jsx" . js))
  (setq org-confirm-babel-evaluate nil)
  (setq org-html-htmlize-output-type 'css))
(load-file "/root/.emacs.d/publish-all.el")
(load-file "/root/.emacs.d/tangle-all.el")
(message (format "Org version: %s" (org-version)))
