(toggle-debug-on-error)
(require 'package)
(setq package-archives
      '(("melpa-stable" . "http://stable.melpa.org/packages/")
        ("melpa" . "https://melpa.org/packages/")
        ("org" . "http://orgmode.org/elpa/")))
(package-initialize)
(package-refresh-contents)
(package-install 'org-plus-contrib)
(package-install 'htmlize)
(package-install 'rainbow-delimiters)
(package-install 'dockerfile-mode)
(package-install 'json-mode)
(package-install 'yaml-mode)
