(toggle-debug-on-error)
(require 'package)
(add-to-list 'package-archives
	     '("melpa-stable" . "http://stable.melpa.org/packages/") t)
(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(package-refresh-contents)
(unless (package-installed-p 'htmlize)
  (package-install 'htmlize))
(unless (package-installed-p 'json-mode)
  (package-install 'json-mode))
(unless (package-installed-p 'js2-mode)
  (package-install 'js2-mode))
(unless (package-installed-p 'rjsx-mode)
  (package-install 'rjsx-mode))
